/**
 * PWA module for @local/dsh-desktop-app.
 *
 * Makes the DSH Web UI installable as a desktop-style app without touching
 * the published frontend dist. It registers exact routes on the `webServer`
 * service (which win over the SPA fallback) and taps every index.html
 * response so the manifest link, theme color and service-worker bootstrap
 * are injected before the dist's own manifest link (the first manifest link
 * in document order wins).
 *
 * Routes:
 *   /dsh-app.webmanifest       application manifest (PNG icons, standalone)
 *   /dsh-app-sw.js             minimal pass-through service worker
 *   /dsh-app-bootstrap.js      registers the service worker on load
 *   /dsh-app-icon-192.png      official black-whale icon, 192x192
 *   /dsh-app-icon-512.png      official black-whale icon, 512x512
 *   /dsh-app-icon-maskable-512.png  maskable icon on a solid background
 */

import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ASSET_DIR = fileURLToPath(new URL('../assets/', import.meta.url))
const assetPath = (name) => join(ASSET_DIR, name)

const MIME = {
  '.webmanifest': 'application/manifest+json; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.png': 'image/png',
}

/** Build the install manifest the plugin serves. Exported for tests. */
export function buildManifest(config) {
  return {
    id: '/',
    name: config.appName,
    short_name: config.shortName,
    description: config.description,
    start_url: '/',
    scope: '/',
    display: 'standalone',
    background_color: config.backgroundColor,
    theme_color: config.themeColor,
    icons: [
      { src: '/dsh-app-icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/dsh-app-icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/dsh-app-icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  }
}

/** Minimal service worker: satisfies installability, never caches. */
export const SERVICE_WORKER = `/* DeepSeek Harness desktop-app service worker (generated by @local/dsh-desktop-app). */
'use strict';
self.addEventListener('install', () => { self.skipWaiting(); });
self.addEventListener('activate', (event) => { event.waitUntil(self.clients.claim()); });
/* The backend is a loopback-only local server: pass every request through. */
self.addEventListener('fetch', (event) => { event.respondWith(fetch(event.request)); });
`

/** Injected into index.html; registers the service worker once loaded. */
export const BOOTSTRAP = `/* DeepSeek Harness desktop-app bootstrap (generated by @local/dsh-desktop-app). */
'use strict';
(() => {
  if (!('serviceWorker' in navigator)) return;
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/dsh-app-sw.js', { scope: '/' })
      .catch(() => { /* local-only enhancement; failure is non-fatal */ });
  });
})();
`

/**
 * Inject the PWA head tags into an index.html body. Idempotent: a document
 * that already carries the plugin's manifest link is returned unchanged.
 * Exported for tests.
 */
export function injectIntoIndex(html, config) {
  if (html.includes('/dsh-app.webmanifest')) return html
  const head =
    '<link rel="manifest" href="/dsh-app.webmanifest" />' +
    `<meta name="theme-color" content="${config.themeColor}" />` +
    '<script src="/dsh-app-bootstrap.js" defer></script>'
  return html.replace('<head>', `<head>${head}`)
}

function send(res, status, type, body) {
  res.writeHead(status, { 'content-type': type, 'cache-control': 'no-store' })
  res.end(body)
}

function serve(body, type) {
  return (req, res) => {
    if (req.method !== 'GET' && req.method !== 'HEAD') {
      res.writeHead(405)
      res.end()
      return
    }
    send(res, 200, type, req.method === 'HEAD' ? undefined : body)
  }
}

/** Mount the PWA routes and index tap on the webServer service. */
export async function applyPwa(ctx, config) {
  const { webServer } = ctx
  const icons = {
    '192': await readFile(assetPath('dsh-app-icon-192.png')),
    '512': await readFile(assetPath('dsh-app-icon-512.png')),
    maskable: await readFile(assetPath('dsh-app-icon-maskable-512.png')),
  }
  const manifestBody = Buffer.from(JSON.stringify(buildManifest(config), null, 2))

  const disposers = [
    webServer.register({ kind: 'exact', path: '/dsh-app.webmanifest', handler: serve(manifestBody, MIME['.webmanifest']) }),
    webServer.register({ kind: 'exact', path: '/dsh-app-sw.js', handler: serve(SERVICE_WORKER, MIME['.js']) }),
    webServer.register({ kind: 'exact', path: '/dsh-app-bootstrap.js', handler: serve(BOOTSTRAP, MIME['.js']) }),
    webServer.register({ kind: 'exact', path: '/dsh-app-icon-192.png', handler: serve(icons['192'], MIME['.png']) }),
    webServer.register({ kind: 'exact', path: '/dsh-app-icon-512.png', handler: serve(icons['512'], MIME['.png']) }),
    webServer.register({ kind: 'exact', path: '/dsh-app-icon-maskable-512.png', handler: serve(icons.maskable, MIME['.png']) }),
    webServer.tapIndex((html) => injectIntoIndex(html, config)),
  ]
  ctx.effect(
    () => () => {
      for (const dispose of disposers) dispose()
    },
    'dsh-desktop-app: pwa routes and index taps',
  )
}
